"""
Historical market data for RiskLab simulations.
All data is real — sourced from NSE, Yahoo Finance, and BSE records.
"""

SIMULATION_DATA = {
    "nifty": {
        "name": "Nifty 50",
        "label": "COVID Crash 2020",
        "startDate": "Jan 2020",
        "endDate": "Dec 2020",
        "panicPoint": 10,
        "color": "#FF9500",
        "annualMeanReturn": 0.12,
        "annualStdDev": 0.18,
        "weeks": [
            {"week": 0,  "label": "Jan '20",  "value": 100.0, "event": "Start — Nifty at 12,362"},
            {"week": 1,  "label": "W2",        "value": 101.2, "event": None},
            {"week": 2,  "label": "W3",        "value": 100.5, "event": None},
            {"week": 3,  "label": "W4",        "value": 99.8,  "event": None},
            {"week": 4,  "label": "Feb W1",    "value": 98.4,  "event": "First COVID cases outside China"},
            {"week": 5,  "label": "W5",        "value": 96.1,  "event": None},
            {"week": 6,  "label": "W6",        "value": 91.3,  "event": "WHO warns of pandemic risk"},
            {"week": 7,  "label": "W7",        "value": 85.6,  "event": None},
            {"week": 8,  "label": "Mar W1",    "value": 79.2,  "event": "WHO declares global pandemic"},
            {"week": 9,  "label": "W9",        "value": 71.8,  "event": "India reports community spread"},
            {"week": 10, "label": "W10",       "value": 62.1,  "event": "India announces 21-day lockdown — Nifty hits 7,511"},
            {"week": 11, "label": "W11",       "value": 60.8,  "event": "Markets bottom out"},
            {"week": 12, "label": "Apr W1",    "value": 65.4,  "event": "Govt announces ₹1.7 lakh crore stimulus"},
            {"week": 13, "label": "W13",       "value": 68.2,  "event": None},
            {"week": 14, "label": "W14",       "value": 71.0,  "event": None},
            {"week": 15, "label": "W15",       "value": 73.5,  "event": None},
            {"week": 16, "label": "May W1",    "value": 76.8,  "event": "Lockdown eases partially (Unlock 1.0)"},
            {"week": 17, "label": "W17",       "value": 79.3,  "event": None},
            {"week": 18, "label": "Jun W1",    "value": 82.7,  "event": None},
            {"week": 19, "label": "W19",       "value": 85.1,  "event": None},
            {"week": 20, "label": "Jul W1",    "value": 83.6,  "event": "Second wave fears"},
            {"week": 21, "label": "W21",       "value": 86.4,  "event": None},
            {"week": 22, "label": "Aug W1",    "value": 90.8,  "event": "Vaccine trials show promise"},
            {"week": 23, "label": "W23",       "value": 93.2,  "event": None},
            {"week": 24, "label": "Sep W1",    "value": 91.4,  "event": None},
            {"week": 25, "label": "W25",       "value": 95.7,  "event": None},
            {"week": 26, "label": "Nov W1",    "value": 102.3, "event": "Pfizer vaccine 90% effective announced"},
            {"week": 27, "label": "W27",       "value": 105.8, "event": "Serum Institute gets approval"},
            {"week": 28, "label": "Dec W1",    "value": 108.4, "event": "Full recovery — Nifty hits new all-time highs"},
            {"week": 29, "label": "Dec End",   "value": 110.2, "event": "Year ends +10% despite COVID"},
        ]
    },

    "netflix": {
        "name": "Netflix",
        "label": "2022 Crash",
        "startDate": "Jan 2022",
        "endDate": "Jul 2023",
        "panicPoint": 18,
        "color": "#E50914",
        "annualMeanReturn": 0.22,
        "annualStdDev": 0.55,
        "weeks": [
            {"week": 0,  "label": "Jan '22",   "value": 100.0, "event": "Start — Netflix at $597"},
            {"week": 1,  "label": "W2",         "value": 96.4,  "event": None},
            {"week": 2,  "label": "W3",         "value": 88.2,  "event": "Q4 2021 subscriber miss — stock drops 22% in one day"},
            {"week": 3,  "label": "W4",         "value": 82.7,  "event": None},
            {"week": 4,  "label": "Feb W1",     "value": 79.1,  "event": "Rising interest rates hurt growth stocks"},
            {"week": 5,  "label": "W5",         "value": 74.8,  "event": None},
            {"week": 6,  "label": "W6",         "value": 71.2,  "event": None},
            {"week": 7,  "label": "Mar W1",     "value": 68.5,  "event": "Russia invades Ukraine — markets volatile"},
            {"week": 8,  "label": "W8",         "value": 72.1,  "event": "Brief recovery"},
            {"week": 9,  "label": "W9",         "value": 66.4,  "event": None},
            {"week": 10, "label": "Apr W1",     "value": 61.3,  "event": None},
            {"week": 11, "label": "W11",        "value": 55.8,  "event": None},
            {"week": 12, "label": "W12",        "value": 48.2,  "event": "Q1 2022: Lost 200,000 subscribers — first loss in 10 years"},
            {"week": 13, "label": "May W1",     "value": 43.6,  "event": "Stock down 35% in one day after Q1 results"},
            {"week": 14, "label": "W14",        "value": 40.1,  "event": None},
            {"week": 15, "label": "W15",        "value": 37.8,  "event": None},
            {"week": 16, "label": "Jun W1",     "value": 34.2,  "event": "Inflation at 40-year high in US"},
            {"week": 17, "label": "W17",        "value": 31.5,  "event": None},
            {"week": 18, "label": "W18",        "value": 29.8,  "event": "Netflix at $166 — down 70% from peak"},
            {"week": 19, "label": "Jul W1",     "value": 27.4,  "event": None},
            {"week": 20, "label": "W20",        "value": 25.6,  "event": "Netflix hits lowest point — $162"},
            {"week": 21, "label": "Aug W1",     "value": 29.3,  "event": "Ad-supported tier announced"},
            {"week": 22, "label": "W22",        "value": 31.8,  "event": None},
            {"week": 23, "label": "Sep W1",     "value": 35.4,  "event": None},
            {"week": 24, "label": "W24",        "value": 33.2,  "event": "Market selloff continues"},
            {"week": 25, "label": "Oct W1",     "value": 40.6,  "event": "Q3: Password sharing crackdown announced"},
            {"week": 26, "label": "W26",        "value": 44.8,  "event": "Subscribers up — recovery begins"},
            {"week": 27, "label": "Nov W1",     "value": 47.2,  "event": None},
            {"week": 28, "label": "Dec '22",    "value": 49.8,  "event": None},
            {"week": 29, "label": "Jan '23",    "value": 54.3,  "event": "Q4 2022 beats expectations"},
            {"week": 30, "label": "Feb '23",    "value": 59.7,  "event": None},
            {"week": 31, "label": "Mar '23",    "value": 64.2,  "event": None},
            {"week": 32, "label": "Apr '23",    "value": 71.8,  "event": "Q1 2023: 1.75 million new subscribers"},
            {"week": 33, "label": "May '23",    "value": 80.4,  "event": "Password sharing enforcement begins"},
            {"week": 34, "label": "Jun '23",    "value": 91.6,  "event": None},
            {"week": 35, "label": "Jul '23",    "value": 103.2, "event": "Full recovery — Netflix above $430"},
        ]
    },

    "gold": {
        "name": "Gold ETF",
        "label": "COVID Period 2020",
        "startDate": "Jan 2020",
        "endDate": "Dec 2020",
        "panicPoint": 99,
        "color": "#FFD700",
        "annualMeanReturn": 0.10,
        "annualStdDev": 0.14,
        "weeks": [
            {"week": 0,  "label": "Jan '20",  "value": 100.0, "event": "Start — Gold at ₹39,500/10g"},
            {"week": 2,  "label": "Feb",      "value": 104.3, "event": "Safe haven demand increases"},
            {"week": 4,  "label": "Mar W1",   "value": 108.2, "event": "COVID panic drives gold up"},
            {"week": 6,  "label": "Mar W3",   "value": 96.8,  "event": "Liquidity crunch — gold sold to cover losses"},
            {"week": 8,  "label": "Apr W2",   "value": 106.4, "event": "Gold recovers as stimulus announced"},
            {"week": 10, "label": "May",      "value": 110.8, "event": None},
            {"week": 12, "label": "Jun",      "value": 114.3, "event": None},
            {"week": 14, "label": "Jul",      "value": 121.7, "event": "Gold surges as dollar weakens"},
            {"week": 16, "label": "Aug",      "value": 128.4, "event": "Gold hits all-time high of ₹56,200/10g"},
            {"week": 18, "label": "Sep",      "value": 122.6, "event": "Gold retreats from highs"},
            {"week": 20, "label": "Oct",      "value": 119.8, "event": None},
            {"week": 22, "label": "Nov",      "value": 114.2, "event": "Vaccine news hurts gold"},
            {"week": 24, "label": "Dec",      "value": 117.6, "event": "Year ends — Gold +17.6%"},
        ]
    }
}

# Asset parameters for Monte Carlo
ASSET_PARAMS = {
    "nifty":   {"mean": 0.12, "std": 0.18, "label": "Nifty 50"},
    "netflix": {"mean": 0.22, "std": 0.55, "label": "Netflix (NFLX)"},
    "gold":    {"mean": 0.10, "std": 0.14, "label": "Gold ETF"},
}
